services:
  - type: web
    name: pekegno-backend
    runtime: docker
    repo: https://github.com/Takou237/pekegno
    branch: master
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://pekegno-backend.onrender.com
      - key: FRONTEND_URL
        value: https://pekegno-frontend.vercel.app
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-eu-west-2.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.hvpqghxxrzyxchzxegse
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: file
      - key: LOG_CHANNEL
        value: stack
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_SCHEME
        value: smtps
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        value: mikeyken848@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: mikeyken848@gmail.com
